# Generated by Django 5.0.3 on 2024-04-02 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_article_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=datetime.datetime(2024, 4, 2, 5, 55, 49, 781064, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
